### ISSUE TITLE
Beats plugin does not accept messages over TLS, shows "unknown_ca" in logs

### ISSUE THREAD

**Issue by e-alfred** [Graylog2/graylog-plugin-beats#8]
Hello,

I am trying to send logs from filebeat/winlogbeat to Graylog running the beats plugin over TLS. If I try to send logs to the server the the following entry appears in the graylog-server log file:

```
2016-07-13T16:12:26.464Z DEBUG [SslHandler] [id: 0xb8fa4642, /141.201.13.205:40470 => /141.201.123.193:5044] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2016-07-13T16:12:26.464Z ERROR [NettyTransport] Error in Input [Beats/5768061314d1a847890cabef] (channel [id: 0xb8fa4642, /141.201.13.205:40470 => /141.201.123.193:5044])
javax.net.ssl.SSLException: Received fatal alert: unknown_ca
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_91]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_91]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218) ~[graylog.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852) ~[graylog.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[graylog.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[graylog.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[graylog.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [graylog.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [graylog.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [graylog.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [graylog.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-07-13T16:12:26.465Z DEBUG [NettyTransport] Could not handle message, closing connection: [id: 0xb8fa4642, /141.201.13.205:40470 => /141.201.123.193:5044] EXCEPTION: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
```

If I try to access the input in a browser for example I see this message:

```
server:5044 uses an invalid security certificate.

The certificate is not trusted because it is self-signed.
The certificate is only valid for 0.0.0.0:null

Error code: SEC_ERROR_UNKNOWN_ISSUER
Peer's Certificate issuer is not recognized. 

HTTP Strict Transport Security: false 
HTTP Public Key Pinning: false 

Certificate chain: 
-----BEGIN CERTIFICATE----- 

-----END CERTIFICATE----- 
```

The certificate is from a real CA (Digicert) and works well in another setup (webserver). I also tried to add the root CA to the Java keystore but it didn't help.

**Comment by joschi** [comment]
@e-alfred Which certificate and which private key did you add to the Beats input in Graylog?

> If I try to access the input in a browser for example I see this message:

Your web browser doesn't support the Beats protocol, so that's kind of expected.

What's the output of `openssl s_client -connect server:5044 -showcerts` when the Beats input is running?

**Comment by e-alfred** [comment]
I added my own certificate singned by a trusted CA (Digicert). Here are the settings (I did not set a TLS key password):

```
    bind_address:
     0.0.0.0
    override_source:
     <empty>
    port:
     5044
    recv_buffer_size:
     <empty>
    tcp_keepalive:
     false
    tls_cert_file:
     /etc/ssl/certs/server.crt
    tls_client_auth:
     disabled
    tls_client_auth_cert_file:
     <empty>
    tls_enable:
     true
    tls_key_file:
     /etc/ssl/private/server.key
    tls_key_password:
     ********
```

Okay, here is the output of `openssl s_client -connect server:5044 -showcerts`:

```
CONNECTED(00000003)
depth=0 CN = 0.0.0.0:null
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = 0.0.0.0:null
verify return:1
---
Certificate chain
 0 s:/CN=0.0.0.0:null
   i:/CN=0.0.0.0:null
-----BEGIN CERTIFICATE-----
MIIBrDCCARWgAwIBAgIJAOozk4qw2k2ZMA0GCSqGSIb3DQEBBQUAMBcxFTATBgNV
BAMTDDAuMC4wLjA6bnVsbDAgFw0xNTA3MTQxNjIxNTZaGA85OTk5MTIzMTIzNTk1
OVowFzEVMBMGA1UEAxMMMC4wLjAuMDpudWxsMIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQCUCpyaINPrJR2HjbfNpj7HiPHKZ5n0v3orgVnscH07ZwfGSAm1TA49
2of32Nja99F6h11qJc5Kbx4Bw5Y+odsBbTo5+B0ZTOVVrpDffmZtUYMy1hO+892V
8CoRQdrL6Y2phkEY5Tp2Af0vkEHtebCXpaAldBU8LH3gX8kRLs+J1QIDAQABMA0G
CSqGSIb3DQEBBQUAA4GBAG0qTTxA/erxekz3IuDcB36RBclfC+2AEqE2Sfbg+MoF
gJdByoow1IZLF3q6S8RaNfZ79xbXvVEt5VMVB+cJtNmPexJ9UQ9UdhU4P44hEryf
5iAI0WSq4WvmYZftYVeg7ARDRqZ2a44gB57nqVgQqVy6QOsrIFFldt76LhLEktbk
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=0.0.0.0:null
issuer=/CN=0.0.0.0:null
---
No client certificate CA names sent
---
SSL handshake has read 868 bytes and written 495 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 5787AFBFA78EB3DA8CA7BD441F4DBD9085D856EB0C1B392245BD7454F71589D1
    Session-ID-ctx: 
    Master-Key: E01B005144933052906871299A96BFEEBE5C4BA48E82E209587AFA7B0B6981F34E4E60C454F9D0ADD3190AD8CC86D805
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1468510143
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---

closed
```

**Comment by joschi** [comment]
@e-alfred This looks like the wrong certificate to me. Make sure that Graylog can read the certificate file and the private key and check the logs of your Graylog node(s) for error messages.

**Comment by e-alfred** [comment]
Do the same requirements as for SSL certificates in Graylog apply? Like those mentioned here: http://docs.graylog.org/en/2.1/pages/configuration/https.html

**Comment by joschi** [comment]
@e-alfred Yes, the same requirements apply (PKCS#8 private key in PEM format, X.509 certificate in PEM format).

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
